#include "esp_sleep.h"
#include "ulp_lp_core.h"
#include "lp_core_i2c.h"
#include "soc/rtc.h"
#include "esp_timer.h"
#include "driver/gpio.h"
#include "driver/rtc_io.h"
#include "esphome/core/log.h"
#include "esphome/core/hal.h"
#include "ulp_ina219.h"

// The following header is automatically generated by the esp idf sdk
// as part of its build process.
#include "ulp_main.h"  // NOLINT(clang-diagnostic-error)
#include "ulp/ulp_types.h"

namespace esphome {
namespace ulp_ina219 {

static const char *const TAG = "ulp_219";
static const uint32_t ULP_INA219_WAIT_TIMEOUT = 10;

// The following references are defined by the esp idf sdk as part of
// the ulp build process and cannot be altered to satisfy the linter.
// NOLINTBEGIN(readability-identifier-naming)
extern const uint8_t lp_core_main_bin_start[] asm("_binary_ulp_main_bin_start");
extern const uint8_t lp_core_main_bin_end[] asm("_binary_ulp_main_bin_end");
// NOLINTEND(readability-identifier-naming)

ulp_ina219_context_t *UlpIna219::get_ulp_context() { return reinterpret_cast<ulp_ina219_context_t *>(&ulp_ctx); }

bool UlpIna219::wait_for_ulp_sleep() {
  ulp_ina219_context_t *ctx = get_ulp_context();
  uint32_t start_time = millis();
  while (ctx->prg_state != PRG_STATE_SLEEP && ctx->prg_state != PRG_STATE_WAIT_SLEEP) {
    if (millis() - start_time > ULP_INA219_WAIT_TIMEOUT) {
      ESP_LOGE(TAG, "timeout wait ulp sleep");
      return false;
    }
    yield();
  }
  return true;
}

bool UlpIna219::is_valid_bus(uint8_t bus_idx) {
  if (bus_idx < MAX_BUS) {
    return true;
  } else {
    ESP_LOGE(TAG, "Invalid bus idx %u", bus_idx);
    return false;
  }
}

void UlpIna219::on_powerdown() {
  volatile ulp_ina219_context_t *ctx = get_ulp_context();
  ctx->main_cpu_awake = false;
}

void UlpIna219::setup() {
  ESP_LOGCONFIG(TAG, "Running setup");

  esp_sleep_wakeup_cause_t cause = esp_sleep_get_wakeup_cause();
  volatile ulp_ina219_context_t *ctx = get_ulp_context();
  ctx->main_cpu_awake = true;

  if (ctx->prg_state == PRG_STATE_NONE || cause == ESP_SLEEP_WAKEUP_UNDEFINED) {
    ulp_lp_core_stop();

    esp_err_t ret = this->lp_i2c_init_();
    if (ret != ESP_OK) {
      this->mark_failed("Unable to initialize ulp i2c");
      return;
    }

    ret = this->lp_core_init_();
    if (ret != ESP_OK) {
      this->mark_failed("Unable to initialize ulp core");
      return;
    }
  } else {
    // Recalibrate the slow clock period
    ctx->slow_clk_period = rtc_clk_cal(RTC_CAL_RTC_MUX, 1000);
    esp_sleep_enable_ulp_wakeup();
    ESP_LOGCONFIG(TAG, "Ulp already running");
  }
}

esp_err_t UlpIna219::lp_core_init_() {
  esp_err_t ret = ESP_OK;

  ulp_lp_core_cfg_t cfg = {.wakeup_source = ULP_LP_CORE_WAKEUP_SOURCE_LP_TIMER,
                           .lp_timer_sleep_duration_us = this->sleep_duration_ * 1000};

  volatile ulp_ina219_context_t *ctx = get_ulp_context();

  ret = ulp_lp_core_load_binary(lp_core_main_bin_start, (lp_core_main_bin_end - lp_core_main_bin_start));
  if (ret != ESP_OK) {
    ESP_LOGD(TAG, "Ulp binary load failed");
    return ret;
  }

  ret = this->lp_rtc_io_init_();
  if (ret != ESP_OK) {
    this->mark_failed("Ulp io init failed");
    return ret;
  }

  ctx->slow_clk_period = rtc_clk_cal(RTC_CAL_RTC_MUX, 1000);

  for (uint8_t i = 0; i < MAX_BUS; ++i) {
    volatile bus_config_t *c = &ctx->buses[i].config;

    if (this->bus_enabled_[i]) {
      ESP_LOGD(TAG, "Bus %c enabled", i == 0 ? 'A' : 'B');
      c->max_system_voltage = this->bus_config_[i].max_system_voltage;
      c->max_system_current = this->bus_config_[i].max_system_current;
      c->address = this->bus_config_[i].address;
      c->shunt_resistance = this->bus_config_[i].shunt_resistance;
      c->current_accum_threshold = this->bus_config_[i].current_accum_threshold;
      c->power_accum_threshold = this->bus_config_[i].power_accum_threshold;
      c->calibration_register_override = this->bus_config_[i].calibration_register_override;
      c->reset = 1;
    } else {
      c->address = 0x0;
      ESP_LOGD(TAG, "Bus %c disabled", 'A' + i);
    }
  }

  ret = ulp_lp_core_run(&cfg);
  if (ret != ESP_OK) {
    ESP_LOGD(TAG, "Ulp start failed");
    return ret;
  }

  ret = esp_sleep_enable_ulp_wakeup();

  if (ret != ESP_OK) {
    ESP_LOGD(TAG, "Ulp wake src enable failed");
    return ret;
  }
  ESP_LOGD(TAG, "Ulp started");
  return ret;
}

esp_err_t UlpIna219::lp_i2c_init_() {
  const lp_core_i2c_cfg_t i2c_cfg = {
      .i2c_pin_cfg =
          {
              .sda_io_num = this->lp_sda_pin_,
              .scl_io_num = this->lp_scl_pin_,
              .sda_pullup_en = this->lp_sda_pullup_en_,
              .scl_pullup_en = this->lp_scl_pullup_en_,
          },
      .i2c_timing_cfg =
          {
              .clk_speed_hz = 400000,  // 400 kHz
          },
      .i2c_src_clk = LP_I2C_SCLK_DEFAULT,  // Default LP I2C source clock
  };
  return lp_core_i2c_master_init(LP_I2C_NUM_0, &i2c_cfg);
}

esp_err_t UlpIna219::lp_rtc_io_init_() {
  esp_err_t ret = ESP_OK;
  volatile ulp_ina219_context_t *ctx = get_ulp_context();
  ctx->led.interval = 0;
  ctx->led.pin = -1;

  if (this->led_pin_ != GPIO_NUM_NC && this->led_interval_ > 0) {
    ret = rtc_gpio_init(this->led_pin_);
    if (ret == ESP_OK) {
      rtc_gpio_set_direction(this->led_pin_, RTC_GPIO_MODE_OUTPUT_ONLY);
      rtc_gpio_pulldown_dis(this->led_pin_);
      rtc_gpio_pullup_dis(this->led_pin_);
      ctx->led.interval = this->led_interval_;
      ctx->led.pin = this->led_pin_;
    }
  }
  return ret;
}

void UlpIna219::reset_values(uint8_t bus_idx) {
  if (bus_idx < MAX_BUS) {
    volatile ulp_ina219_context_t *ctx = get_ulp_context();
    volatile bus_config_t *c = &ctx->buses[bus_idx].config;
    volatile bus_values_t *v = &ctx->buses[bus_idx].values;
    if (wait_for_ulp_sleep()) {
      v->charge_in = 0;
      v->charge_out = 0;
      v->charge_net = 0;
      v->energy_in = 0;
      v->energy_out = 0;
      v->energy_net = 0;
      v->voltage_min = v->voltage;
      v->voltage_max = v->voltage;
      v->current_min = v->current;
      v->current_max = v->current;
      this->update();
    } else {
      ESP_LOGE(TAG, "reset values failed");
    }
  } else {
    ESP_LOGE(TAG, "Invalid bus idx %u", bus_idx);
  }
}

void UlpIna219::set_net_charge(uint8_t bus_idx, double charge) {
  if (bus_idx < MAX_BUS) {
    volatile ulp_ina219_context_t *ctx = get_ulp_context();
    volatile bus_values_t *v = &ctx->buses[bus_idx].values;
    if (wait_for_ulp_sleep()) {
      v->charge_net = charge;
      if (this->charge_net_sensor_[bus_idx] != nullptr) {
        this->charge_net_sensor_[bus_idx]->publish_state(v->charge_net);
      }
    } else {
      ESP_LOGE(TAG, "net_charge not set");
    }
  } else {
    ESP_LOGE(TAG, "Invalid bus idx %u", bus_idx);
  }
}

void UlpIna219::set_net_energy(uint8_t bus_idx, double energy) {
  if (bus_idx < MAX_BUS) {
    volatile ulp_ina219_context_t *ctx = get_ulp_context();
    volatile bus_values_t *v = &ctx->buses[bus_idx].values;
    if (wait_for_ulp_sleep()) {
      v->energy_net = energy;
      if (this->energy_net_sensor_[bus_idx] != nullptr) {
        this->energy_net_sensor_[bus_idx]->publish_state(v->energy_net);
      }
    } else {
      ESP_LOGE(TAG, "net_energy not set");
    }
  } else {
    ESP_LOGE(TAG, "Invalid bus idx %u", bus_idx);
  }
}

void UlpIna219::update() {
  volatile ulp_ina219_context_t *ctx = get_ulp_context();

  for (uint8_t i = 0; i < MAX_BUS; ++i) {
    if (!this->bus_enabled_[i])
      continue;

    volatile bus_values_t *b = &ctx->buses[i].values;
    volatile bus_config_t *c = &ctx->buses[i].config;

    ESP_LOGD(TAG,
             "Bus %c:\n"
             "  Calibration register: %u\n"
             "  Current LSB: %u\n",
             'A' + i, b->calibration_register, b->current_lsb);

    esp_err_t bus_error_code = b->error_code;
    if (bus_error_code != ESP_OK) {
      ESP_LOGD(TAG, "Bus errored, code: 0x%X", bus_error_code);
      this->mark_failed("error reading device");
      continue;
    }

    if (this->voltage_sensor_[i] != nullptr) {
      this->voltage_sensor_[i]->publish_state(b->voltage);
    }

    if (this->current_sensor_[i] != nullptr) {
      this->current_sensor_[i]->publish_state(b->current);
    }

    if (this->power_sensor_[i] != nullptr) {
      this->power_sensor_[i]->publish_state(b->power);
    }

    if (this->shunt_voltage_sensor_[i] != nullptr) {
      this->shunt_voltage_sensor_[i]->publish_state(b->shunt_voltage);
    }

    if (this->energy_net_sensor_[i] != nullptr) {
      this->energy_net_sensor_[i]->publish_state(b->energy_net);
    }

    if (this->charge_net_sensor_[i] != nullptr) {
      this->charge_net_sensor_[i]->publish_state(b->charge_net);
    }

    if (this->energy_in_sensor_[i] != nullptr) {
      this->energy_in_sensor_[i]->publish_state(b->energy_in);
    }

    if (this->charge_in_sensor_[i] != nullptr) {
      this->charge_in_sensor_[i]->publish_state(b->charge_in);
    }

    if (this->energy_out_sensor_[i] != nullptr) {
      this->energy_out_sensor_[i]->publish_state(b->energy_out);
    }

    if (this->charge_out_sensor_[i] != nullptr) {
      this->charge_out_sensor_[i]->publish_state(b->charge_out);
    }

    if (this->voltage_max_sensor_[i] != nullptr) {
      this->voltage_max_sensor_[i]->publish_state(b->voltage_max);
    }

    if (this->voltage_min_sensor_[i] != nullptr) {
      this->voltage_min_sensor_[i]->publish_state(b->voltage_min);
    }

    if (this->current_max_sensor_[i] != nullptr) {
      this->current_max_sensor_[i]->publish_state(b->current_max);
    }

    if (this->current_min_sensor_[i] != nullptr) {
      this->current_min_sensor_[i]->publish_state(b->current_min);
    }

    if (this->power_max_sensor_[i] != nullptr) {
      this->power_max_sensor_[i]->publish_state(b->power_max);
    }

    if (this->power_min_sensor_[i] != nullptr) {
      this->power_min_sensor_[i]->publish_state(b->power_min);
    }
  }

  ESP_LOGD(TAG,
           "ulp debug:\n"
           "  run dur: %.3f ms\n"
           "  slow clk: %u\n"
           "  state: %u\n"
           "  led cntr: %u",
           (float) ctx->run_duration / 1000.f, ctx->slow_clk_period, ctx->prg_state, ctx->led.counter);
}

void UlpIna219::dump_config() {
  ESP_LOGCONFIG(TAG,
                "ULP INA219:\n"
                "  Sleep Duration: %d\n"
                "  LP I2C:\n"
                "    SDA Pin: %d\n"
                "    SDA Pullup Enabled: %d\n"
                "    SCL Pin: %d\n"
                "    SCL Pullup Enabled: %d\n"
                "  led:\n"
                "    pin: %d\n"
                "    interval: %d\n",
                this->sleep_duration_, this->lp_sda_pin_, this->lp_sda_pullup_en_, this->lp_scl_pin_,
                this->lp_scl_pullup_en_, this->led_pin_, this->led_interval_);

  for (uint8_t i = 0; i < MAX_BUS; ++i) {
    volatile ulp_ina219_context_t *ctx = get_ulp_context();
    volatile bus_config_t *c = &ctx->buses[i].config;
    if (this->bus_enabled_[i]) {
      ESP_LOGCONFIG(TAG,
                    "Bus %c:\n"
                    "  Address: 0x%X\n"
                    "  Shunt Resistance: %f\n"
                    "  Max Voltage: %f\n"
                    "  Max Current: %f\n"
                    "  Current Accumulation Threshold: %f\n"
                    "  Power Accumulation Threshold: %f\n"
                    "  Calibration Register: %u",
                    'A' + i, c->address, c->shunt_resistance, c->max_system_voltage, c->max_system_current,
                    c->current_accum_threshold, c->power_accum_threshold, c->calibration_register_override);
      LOG_SENSOR("  ", "Voltage", this->voltage_sensor_[i]);
      LOG_SENSOR("  ", "Current", this->current_sensor_[i]);
      LOG_SENSOR("  ", "Power", this->power_sensor_[i]);
      LOG_SENSOR("  ", "Shunt Voltage", this->shunt_voltage_sensor_[i]);
      LOG_SENSOR("  ", "Energy (Net)", this->energy_net_sensor_[i]);
      LOG_SENSOR("  ", "Energy (In)", this->energy_in_sensor_[i]);
      LOG_SENSOR("  ", "Energy (Out)", this->energy_out_sensor_[i]);
      LOG_SENSOR("  ", "Charge (Net)", this->charge_net_sensor_[i]);
      LOG_SENSOR("  ", "Charge (In)", this->charge_in_sensor_[i]);
      LOG_SENSOR("  ", "Charge (Out)", this->charge_out_sensor_[i]);
      LOG_SENSOR("  ", "Voltage (max)", this->voltage_max_sensor_[i]);
      LOG_SENSOR("  ", "Voltage (min)", this->voltage_min_sensor_[i]);
      LOG_SENSOR("  ", "Current (max)", this->current_max_sensor_[i]);
      LOG_SENSOR("  ", "Current (min)", this->current_min_sensor_[i]);
      LOG_SENSOR("  ", "Power (max)", this->power_max_sensor_[i]);
      LOG_SENSOR("  ", "Power (min)", this->power_min_sensor_[i]);
    }
  }

  LOG_UPDATE_INTERVAL(this);
  if (this->is_failed()) {
    ESP_LOGE(TAG, ESP_LOG_MSG_COMM_FAIL);
  }
}

}  // namespace ulp_ina219
}  // namespace esphome
