#include "esp_sleep.h"
#include "ulp_lp_core.h"  // NOLINT(clang-diagnostic-error)
#include "lp_core_i2c.h"
#include "soc/rtc.h"
#include "soc/gpio_num.h"
#include "esp_timer.h"
#include "driver/gpio.h"
#include "driver/rtc_io.h"
#include "esphome/core/gpio.h"
#include "esphome/core/log.h"
#include "esphome/core/hal.h"
#include "ulp_ina219.h"

// The following header is automatically generated by the esp idf sdk
// as part of its build process.
#include "ulp_main.h"  // NOLINT(clang-diagnostic-error)
#include "ulp/common.h"

namespace esphome {
namespace ulp_ina219 {

static const char *const TAG = "ulp_ina219";
static const uint32_t ULP_INA219_WAIT_TIMEOUT = 10;

// The following references are defined by the esp idf sdk as part of
// the ulp build process and cannot be altered to satisfy the linter.
// NOLINTBEGIN(readability-identifier-naming)
extern const uint8_t lp_core_main_bin_start[] asm("_binary_ulp_main_bin_start");
extern const uint8_t lp_core_main_bin_end[] asm("_binary_ulp_main_bin_end");
// NOLINTEND(readability-identifier-naming)

ulp_ina219_context_t *UlpIna219::get_ulp_context() { return reinterpret_cast<ulp_ina219_context_t *>(&ulp_ctx); }

void UlpIna219::setup() {
  ESP_LOGCONFIG(TAG, "Running setup");

  volatile ulp_ina219_context_t *ctx = get_ulp_context();
  ctx->main_cpu_awake = true;

  if (this->ulp_program_load_status_ == ULP_PROGRAM_LOAD_PREV) {
    // Recalibrate the slow clock period
    ctx->slow_clk_period = rtc_clk_cal(RTC_CAL_RTC_MUX, 1000);
    esp_sleep_enable_ulp_wakeup();
    ESP_LOGCONFIG(TAG, "ulp already running");
    return;
  }

  if (this->ulp_program_load_status_ == ULP_PROGRAM_LOAD_COMPLETE) {
    esp_err_t ret = this->ulp_i2c_init_();
    if (ret != ESP_OK) {
      ESP_LOGE(TAG, "ulp i2c init err: %u", ret);
      this->mark_failed();
      return;
    }

    ret = this->ulp_rtc_io_init_();
    if (ret != ESP_OK) {
      ESP_LOGE(TAG, "ulp io init err: %u", ret);
      this->mark_failed();
      return;
    }

    ret = this->ulp_core_init_();
    if (ret != ESP_OK) {
      ESP_LOGE(TAG, "ulp core init err: %u", ret);
      this->mark_failed();
      return;
    }
  } else {
    this->mark_failed("invalid ulp program state");
  }
}

UlpProgramLoadStatusEnum UlpIna219::lp_core_load_program_() {
  esp_sleep_wakeup_cause_t cause = esp_sleep_get_wakeup_cause();
  volatile ulp_ina219_context_t *ctx = get_ulp_context();

  if (ctx->prg_state == PRG_STATE_NONE || cause == ESP_SLEEP_WAKEUP_UNDEFINED) {
    ulp_lp_core_stop();
    esp_err_t ret = ulp_lp_core_load_binary(lp_core_main_bin_start, (lp_core_main_bin_end - lp_core_main_bin_start));
    if (ret == ESP_OK) {
      return ULP_PROGRAM_LOAD_COMPLETE;
    } else {
      ESP_LOGE(TAG, "ulp prg load err: %u", ret);
      return ULP_PROGRAM_LOAD_ERROR;
    }
  }

  return ULP_PROGRAM_LOAD_PREV;
}

esp_err_t UlpIna219::ulp_core_init_() {
  esp_err_t ret = ESP_OK;

  ulp_lp_core_cfg_t cfg = {.wakeup_source = ULP_LP_CORE_WAKEUP_SOURCE_LP_TIMER,
                           .lp_timer_sleep_duration_us = this->sleep_duration_ * 1000};

  volatile ulp_ina219_context_t *ctx = get_ulp_context();

  ctx->slow_clk_period = rtc_clk_cal(RTC_CAL_RTC_MUX, 1000);

  for (uint8_t i = 0; i < MAX_BUS; ++i) {
    volatile bus_config_t *c = &ctx->buses[i].config;

    if (c->address > 0) {
      ESP_LOGD(TAG, "Bus %c enabled", i == 0 ? 'A' : 'B');
      c->reset_min_max = true;
      c->reset_accumulators = true;
    } else {
      c->address = 0x0;
      ESP_LOGD(TAG, "Bus %c disabled", 'A' + i);
    }
  }

  ret = ulp_lp_core_run(&cfg);
  if (ret != ESP_OK) {
    ESP_LOGD(TAG, "ulp start err");
    return ret;
  }

  ret = esp_sleep_enable_ulp_wakeup();

  if (ret != ESP_OK) {
    ESP_LOGD(TAG, "ulp wake src enable err");
    return ret;
  }
  ESP_LOGD(TAG, "ulp started");
  return ret;
}

esp_err_t UlpIna219::ulp_i2c_init_() {
  if (this->lp_scl_pin_ == nullptr || this->lp_sda_pin_ == nullptr) {
    this->mark_failed("lp i2c pins null");
    return ESP_FAIL;
  }
  const lp_core_i2c_cfg_t i2c_cfg = {
      .i2c_pin_cfg =
          {
              .sda_io_num = gpio_num_t(this->lp_sda_pin_->get_pin()),
              .scl_io_num = gpio_num_t(this->lp_scl_pin_->get_pin()),
              .sda_pullup_en = this->lp_scl_pin_->get_flags() & gpio::FLAG_PULLUP ? true : false,
              .scl_pullup_en = this->lp_scl_pin_->get_flags() & gpio::FLAG_PULLUP ? true : false,
          },
      .i2c_timing_cfg =
          {
              .clk_speed_hz = 400000,  // 400 kHz
          },
      .i2c_src_clk = LP_I2C_SCLK_DEFAULT,  // Default LP I2C source clock
  };
  return lp_core_i2c_master_init(LP_I2C_NUM_0, &i2c_cfg);
}

esp_err_t UlpIna219::ulp_rtc_io_init_() {
  esp_err_t ret = ESP_OK;
  volatile ulp_ina219_context_t *ctx = get_ulp_context();
  ctx->led.interval = 0;
  ctx->led.pin = -1;
  gpio_num_t led_pin = this->led_pin_ == nullptr ? GPIO_NUM_NC : gpio_num_t(this->led_pin_->get_pin());

  if (led_pin != GPIO_NUM_NC && this->led_interval_ > 0) {
    ret = rtc_gpio_init(led_pin);
    if (ret == ESP_OK) {
      rtc_gpio_set_direction(led_pin, RTC_GPIO_MODE_OUTPUT_ONLY);
      rtc_gpio_pulldown_dis(led_pin);
      rtc_gpio_pullup_dis(led_pin);
      ctx->led.interval = this->led_interval_;
      ctx->led.pin = led_pin;
      ctx->led.inverted = this->led_pin_->is_inverted();
    }
  }
  return ret;
}

void UlpIna219::on_powerdown() {
  volatile ulp_ina219_context_t *ctx = get_ulp_context();
  ctx->main_cpu_awake = false;
  for (uint8_t i = 0; i < MAX_BUS; ++i) {
    ctx->buses[i].config.reset_min_max = true;
  }
}

void UlpIna219::enable_ulp_wake_src() {
  esp_err_t ret = esp_sleep_enable_ulp_wakeup();
  if (ret == ESP_OK) {
    volatile ulp_ina219_context_t *ctx = get_ulp_context();
    ctx->alarms_enabled = true;
  } else {
    ESP_LOGE(TAG, "triggers disabled, ulp wake en err: %d", ret);
  }
}

void UlpIna219::reset_triggers(uint8_t bus_idx) {
  if (is_valid_bus(bus_idx)) {
    volatile ulp_ina219_context_t *ctx = get_ulp_context();
    volatile alarm_t *t = ctx->buses[bus_idx].alarms;
    uint64_t current_time = lp_core_rtc_ticks_to_us(lp_core_get_rtc_ticks(), ctx->slow_clk_period);

    for (uint8_t i = 0; i < MAX_ALARMS; ++i) {
      if (t[i].status != ALARM_NOT_SET) {
        t[i].status = ALARM_SET;
        t[i].last_fired_us = current_time;
        if (t[i].mode == ALARM_MODE_CHARGE_DELTA || t[i].mode == ALARM_MODE_ENERGY_DELTA) {
          t[i].condition.delta.baseline = INFINITY;
        }
      }
    }
  }
}

void UlpIna219::set_alarm(uint8_t bus_idx, uint8_t alarm_idx, alarm_mode_enum_t mode, uint32_t debounce_ms, float above,
                          float below, float threshold) {
  if (is_valid_bus(bus_idx) && this->ulp_program_load_status_ == ULP_PROGRAM_LOAD_COMPLETE) {
    if (alarm_idx < MAX_ALARMS) {
      volatile ulp_ina219_context_t *ctx = get_ulp_context();
      volatile alarm_t *t = ctx->buses[bus_idx].alarms;

      ctx->alarms_enabled = true;
      t[alarm_idx].status = ALARM_SET;
      t[alarm_idx].mode = mode;
      t[alarm_idx].debounce_us = debounce_ms * 1000;
      if (mode == ALARM_MODE_CHARGE_DELTA || mode == ALARM_MODE_ENERGY_DELTA) {
        t[alarm_idx].condition.delta.threshold = threshold;
        t[alarm_idx].condition.delta.baseline = INFINITY;
      } else {
        t[alarm_idx].condition.range.above = above;
        t[alarm_idx].condition.range.below = below;
      }
    } else {
      ESP_LOGE(TAG, "Invalid alarm idx %u", alarm_idx);
    }
  }
}

bool UlpIna219::wait_for_ulp_sleep() {
  ulp_ina219_context_t *ctx = get_ulp_context();
  uint32_t start_time = millis();
  while (ctx->prg_state != PRG_STATE_SLEEP && ctx->prg_state != PRG_STATE_WAIT_SLEEP) {
    if (millis() - start_time > ULP_INA219_WAIT_TIMEOUT) {
      ESP_LOGE(TAG, "timeout wait on ulp sleep");
      return false;
    }
    yield();
  }
  return true;
}

void UlpIna219::reset_values(uint8_t bus_idx) {
  if (is_valid_bus(bus_idx)) {
    volatile ulp_ina219_context_t *ctx = get_ulp_context();
    volatile bus_config_t *c = &ctx->buses[bus_idx].config;
    volatile bus_values_t *v = &ctx->buses[bus_idx].values;
    if (wait_for_ulp_sleep()) {
      v->charge_in = 0;
      v->charge_out = 0;
      v->charge_net = 0;
      v->energy_in = 0;
      v->energy_out = 0;
      v->energy_net = 0;
      v->voltage_min = v->voltage;
      v->voltage_max = v->voltage;
      v->current_min = v->current;
      v->current_max = v->current;
    } else {
      ESP_LOGE(TAG, "reset values err");
    }
  }
}

void UlpIna219::set_net_charge(uint8_t bus_idx, float charge) {
  if (bus_idx < MAX_BUS) {
    volatile ulp_ina219_context_t *ctx = get_ulp_context();
    volatile bus_values_t *v = &ctx->buses[bus_idx].values;
    if (wait_for_ulp_sleep()) {
      v->charge_net = charge;
    } else {
      ESP_LOGE(TAG, "net_charge not set");
    }
  } else {
    ESP_LOGE(TAG, "Invalid bus idx %u", bus_idx);
  }
}

void UlpIna219::set_net_energy(uint8_t bus_idx, float energy) {
  if (bus_idx < MAX_BUS) {
    volatile ulp_ina219_context_t *ctx = get_ulp_context();
    volatile bus_values_t *v = &ctx->buses[bus_idx].values;
    if (wait_for_ulp_sleep()) {
      v->energy_net = energy;
    } else {
      ESP_LOGE(TAG, "net_energy not set");
    }
  } else {
    ESP_LOGE(TAG, "Invalid bus idx %u", bus_idx);
  }
}

bool UlpIna219::is_valid_bus(uint8_t bus_idx) {
  if (bus_idx < MAX_BUS) {
    return true;
  } else {
    ESP_LOGE(TAG, "Invalid bus idx %u", bus_idx);
    return false;
  }
}

void UlpIna219::dump_config() {
  ESP_LOGCONFIG(TAG,
                "ULP INA219:\n"
                "  Sleep Duration: %u ms\n"
                "  LP I2C:\n",
                this->sleep_duration_);
  LOG_PIN("    sda: ", this->lp_sda_pin_);
  ESP_LOGCONFIG(TAG, "      pull up: %s", ONOFF(this->lp_sda_pin_->get_flags() & gpio::FLAG_PULLUP));
  LOG_PIN("    scl: ", this->lp_scl_pin_);
  ESP_LOGCONFIG(TAG, "      pull up: %s", ONOFF(this->lp_scl_pin_->get_flags() & gpio::FLAG_PULLUP));
  ESP_LOGCONFIG(TAG, "  Activity Led:");
  LOG_PIN("    pin: ", this->led_pin_);
  ESP_LOGCONFIG(TAG, "    interval: %u", this->led_interval_);

  for (uint8_t i = 0; i < MAX_BUS; ++i) {
    volatile ulp_ina219_context_t *ctx = get_ulp_context();
    volatile bus_config_t *c = &ctx->buses[i].config;
    volatile alarm_t *t = ctx->buses[i].alarms;
    if (c->address > 0) {
      ESP_LOGCONFIG(TAG,
                    "  Bus %u:\n"
                    "    Address: 0x%X\n"
                    "    Shunt Resistance: %f\n"
                    "    Max Voltage: %f\n"
                    "    Max Current: %f\n"
                    "    Current Accumulation Threshold: %f\n"
                    "    Power Accumulation Threshold: %f\n"
                    "    Calibration Register: %u",
                    i, c->address, c->shunt_resistance, c->max_system_voltage, c->max_system_current,
                    c->current_accum_threshold, c->power_accum_threshold, c->calibration_register_override);
    }
  }

  if (this->is_failed()) {
    ESP_LOGE(TAG, ESP_LOG_MSG_COMM_FAIL);
  }
}

}  // namespace ulp_ina219
}  // namespace esphome
